"""Add status field to test run model

Revision ID: 12340edd992d
Revises: 1e2c38f575fb
Create Date: 2013-07-03 17:38:42.632146

"""

# revision identifiers, used by Alembic.
revision = '12340edd992d'
down_revision = '1e2c38f575fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('status', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'status')
    ### end Alembic commands ###
