"""Storage refactor

Revision ID: 1e2c38f575fb
Revises: 1fcb29d29e03
Create Date: 2013-07-02 22:43:00.844574

"""

# revision identifiers, used by Alembic.
revision = '1e2c38f575fb'
down_revision = '1fcb29d29e03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_sets',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'test_runs', sa.Column('external_id', sa.String(length=128), nullable=True))
    op.add_column(u'test_runs', sa.Column('stats', sa.Text(), nullable=True))
    op.add_column(u'tests', sa.Column('test_set_id', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'tests', 'test_set_id')
    op.drop_column(u'test_runs', 'stats')
    op.drop_column(u'test_runs', 'external_id')
    op.drop_table('test_sets')
    ### end Alembic commands ###
