"""Add started_at , ended_at on TestRun model

Revision ID: 4e9905279776
Revises: 12340edd992d
Create Date: 2013-07-04 12:10:49.219213

"""

# revision identifiers, used by Alembic.
revision = '4e9905279776'
down_revision = '12340edd992d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('test_runs', sa.Column('ended_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'ended_at')
    op.drop_column('test_runs', 'started_at')
    ### end Alembic commands ###
