"""Test model taken field - Time to Float

Revision ID: 163e0c119e12
Revises: b739e5a3653
Create Date: 2013-06-18 10:46:12.304309

"""

# revision identifiers, used by Alembic.
revision = '163e0c119e12'
down_revision = 'b739e5a3653'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
